### ISSUE TITLE
stopped maintaining?

### ISSUE THREAD

**Issue by D0P3R030T** [woj-ciech/LeakLooker-X#29]
(newenv) sventek@fuckyou:~/tools/LeakLooker-X$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
                 ^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    if getattr(settings, 'ROOT_URLCONF', None):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sventek/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/sventek/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/LeakLooker-X/manage.py", line 21, in <module>
    main()
  File "/home/sventek/tools/LeakLooker-X/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
                ^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
                      ^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sventek/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/sventek/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
(newenv) sventek@fuckyou:~/tools/LeakLooker-X$ python3 manage.py migrate
Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
                 ^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 63, in _run_checks
    issues = run_checks(tags=[Tags.database])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
                ^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 222, in all
    return [self[alias] for alias in self]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
                ^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
                      ^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sventek/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/sventek/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/LeakLooker-X/manage.py", line 21, in <module>
    main()
  File "/home/sventek/tools/LeakLooker-X/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
                ^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
                      ^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sventek/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/sventek/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
(newenv) sventek@fuckyou:~/tools/LeakLooker-X$ python3 manage.py runserver
Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
           ^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sventek/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/sventek/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sventek/tools/LeakLooker-X/manage.py", line 21, in <module>
    main()
  File "/home/sventek/tools/LeakLooker-X/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
                ^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
                      ^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sventek/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/sventek/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/home/sventek/tools/newenv/lib/python3.11/site-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

**Comment by D0P3R030T** [comment]
is this the reason?
if so, how to fix

The function [inspect.formatargspec](https://docs.python.org/3.10/library/inspect.html#inspect.formatargspec) was last available in Python 3.10 as it was marked as deprecation as per its documentation since Python 3.5, and was noted to be [removed](https://docs.python.org/3.11/whatsnew/3.11.html#removed) as per the release notes of Python 3.11.
