### ISSUE TITLE
User experience issue dropdown

### ISSUE THREAD

**Issue by danieleperera** [woj-ciech/LeakLooker-X#3]
Hi, I have been using LeakLooker-X GUI for last few days. I find the dropdown to select the type of DBs a little bit tedious. Most of the time I want to select all DBs so selecting one by one in a dropdown menu is hard. Maybe it would be easy to have an unordered-list of checkboxes and a checkbox 'select all'. Which selects all DBs. What do you think? I can work on it

![Annotazione 2020-03-24 150045](https://user-images.githubusercontent.com/45230107/77433866-453dc780-6de0-11ea-9c3a-0758cbd27433.png)

**Comment by woj-ciech** [comment]
Hey, it's literally theme from https://www.cssscript.com/multi-select-autocomplete-2/. I'm not into frontend but if you can push some code to change that would be cool.

**Comment by dop3st** [comment]
┌──(user001㉿Alpha)-[~/tools/LeakLooker-X]
└─$ python3 manage.py runserver
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/commands/runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user001/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/user001/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/usr/local/lib/python3.11/dist-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python3.11/dist-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/usr/local/lib/python3.11/dist-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/usr/local/lib/python3.11/dist-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/usr/local/lib/python3.11/dist-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/vine/five.py", line 361, in <module>
    from inspect import formatargspec, getfullargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user001/tools/LeakLooker-X/manage.py", line 21, in <module>
    main()
  File "/home/user001/tools/LeakLooker-X/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user001/tools/LeakLooker-X/leaklooker/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/home/user001/tools/LeakLooker-X/leaklooker/celery.py", line 3, in <module>
    from celery import Celery
  File "/usr/local/lib/python3.11/dist-packages/celery/__init__.py", line 17, in <module>
    from . import local  # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python3.11/dist-packages/celery/five.py", line 7, in <module>
    import vine.five
  File "/usr/local/lib/python3.11/dist-packages/vine/__init__.py", line 8, in <module>
    from .abstract import Thenable
  File "/usr/local/lib/python3.11/dist-packages/vine/abstract.py", line 6, in <module>
    from .five import with_metaclass, Callable
  File "/usr/local/lib/python3.11/dist-packages/vine/five.py", line 364, in <module>
    from inspect import formatargspec, getargspec as _getargspec  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
