### ISSUE TITLE
Problem with LeakLooker, macOS

### ISSUE THREAD

**Issue by mayhem78** [woj-ciech/LeakLooker-X#7]
So I have this error when trying to run a search with LeakLooker:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/xxx/Documents/SRC/scripts/leaklooker-NEW/LeakLooker-X-master/leaklooker_app/views.py", line 246, in stats_db
    model = apps.get_model('leaklooker_app', type)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 210, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 180, in get_model
    raise LookupError(
LookupError: App 'leaklooker_app' doesn't have a 'undefined' model.
```

**Comment by woj-ciech** [comment]
I tried to recreate the issue but I couldn't. However this are the steps I take when something goes wrong.
1. Delete sql3 file and everything from "migrations" directory except "__init__.py". Make sure that redis and celery is running as root and there was no problem during database migrations.
2. Create a new virtual environment. I use pycharm - https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html
3. This answer also might help https://stackoverflow.com/a/33851227
