### ISSUE TITLE
Object of type 'KeyError' is not JSON serializable

### ISSUE THREAD

**Issue by ghost** [woj-ciech/LeakLooker-X#8]
```
[06/Sep/2020 16:24:19] "GET /keyword/search?country=&keyword=test&network=&type=Mongo HTTP/1.1" 200 68
{'pid': 2393, 'hostname': 'celery@vps-**.vps-default-host.net'}
{'state': 'STARTED', 'result': {'pid': 2393, 'hostname': 'celery@vps-**.vps-default-host.net'}}
[06/Sep/2020 16:24:19] "GET /get-task-info/?task_id=2cb32033-78e7-4f8c-b256-7b2f00425b1e HTTP/1.1" 200 98
{'pid': 2393, 'hostname': 'celery@vps-***.vps-default-host.net'}
{'state': 'STARTED', 'result': {'pid': 2393, 'hostname': 'celery@vps-**.vps-default-host.net'}}
[06/Sep/2020 16:24:19] "GET /get-task-info/?task_id=2cb32033-78e7-4f8c-b256-7b2f00425b1e HTTP/1.1" 200 98
'events'
{'state': 'FAILURE', 'result': KeyError('events',)}
Internal Server Error: /get-task-info/
Traceback (most recent call last):
  File "/home/LeakLooker-X/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/LeakLooker-X/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/LeakLooker-X/leaklooker_app/views.py", line 183, in get_task_info
    return HttpResponse(json.dumps(data), content_type='application/json')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable
[06/Sep/2020 16:24:19] "GET /get-task-info/?task_id=2cb32033-78e7-4f8c-b256-7b2f00425b1e HTTP/1.1" 500 80894
```

**Comment by woj-ciech** [comment]
I can't reproduce this error now but I remember I came across this during development.
Make sure to delete migrations and your db and migrate it again. If it won't help you should set up new virtual environment and repeat installation process.

**Comment by ghost** [comment]
> I can't reproduce this error now but I remember I came across this during development.
> Make sure to delete migrations and your db and migrate it again. If it won't help you should set up new virtual environment and repeat installation process.

now work(

celery logs:
```
[2020-09-14 15:33:52,761: ERROR/ForkPoolWorker-1] Task leaklooker.tasks.check_main[92495b81-1b17-4953-9d1a-f285d07edf0d] raised unexpected: KeyError('events',)
Traceback (most recent call last):
  File "/home/LeakLooker-X/venv/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/LeakLooker-X/venv/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/LeakLooker-X/leaklooker/tasks.py", line 122, in check_main
    total = len(req_json['events'])
KeyError: 'events'
```

UPD:

i'm run celery -A leaklooker beat --loglevel=info and it's work but:
```
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:04] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:05] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:05] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:06] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:06] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:07] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:07] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:08] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
None
{'state': 'PENDING', 'result': None}
[14/Sep/2020 15:45:08] "GET /get-task-info/?task_id=b715f675-a781-4a81-ac23-2b8505462df2 HTTP/1.1" 200 36
```

it's normal?
